#!/bin/sh
#
# BEFORE: DAEMON
# PROVIDE: ezjail-config
#

. /etc/rc.subr

name=ezjail-config
start_cmd=flavour_setup

flavour_setup() {

# Remove traces of ourself
# N.B.: Do NOT rm $0, it points to /etc/rc
##########################
rm -f "/etc/rc.d/ezjail-config"

# Groups
#########
#
# You will probably start with some groups your users should be in

# pw groupadd -q -n coders # -g 1004
# pw groupadd -q -n sales # -g 1005

# Users
########
#
# You might want to add some users. The password is to be provided in the
# encrypted form as found in /etc/master.passwd.
# The example password here is "admin"
# Refer to crypt(3) and pw(8) for more information

# echo -n '$1$p75bbfK.$Kz3dwkoVlgZrfLZdAXQt91' |\
# pw useradd -n admin -u 1001 -s /bin/sh -m -d /home/admin -G wheel -c 'Admin User' -H 0
# echo -n '$1$p75bbfK.$Kz3dwkoVlgZrfLZdAXQt91' |\
# pw useradd -n saag -u 1002 -s /bin/sh -m -d /home/saag -G coders -c 'Mutton Saag' -H 0
# echo -n '$1$p75bbfK.$Kz3dwkoVlgZrfLZdAXQt91' |\
# pw useradd -n mac -u 1002 -s /bin/sh -m -d /home/mac -G sales -c 'Big Mac' -H 0

# Packages
###########
#
# Install all packages previously put to /pkg
# Remove package files afterwards

cd /usr/ports/ports-mgmt/pkg && make install clean

pkg update

# [ -d /pkg ] && cd /pkg && pkg_add /pkg/*
# rm -rf /pkg

# Install packages need to install alignak
pkg install -y git
pkg install -y py27-pip
pkg install -y iconv

# install packages used for website scenarii
#pkg install -y ruby23-gems
pkg install -y rubygem-capybara

/usr/local/bin/gem install iconv
/usr/local/bin/gem install cucumber-nagios

# install alignak
#################

cd /root
mkdir git
cd git
/usr/local/bin/git clone https://github.com/Alignak-monitoring/alignak.git
cd alignak
/usr/local/bin/pip install .

# get rc scripts to start alignak
cd ..
/usr/local/bin/git clone https://github.com/Alignak-monitoring/alignak-packaging.git
cd alignak-packaging/alignak/for_freebsd
cp alignak-* /usr/local/etc/rc.d/

# add lines in rc.conf to start alignak when start the jail
echo 'alignak_broker_enable="YES"' >> /etc/rc.conf
echo "\n";
echo 'alignak_poller_enable="YES"' >> /etc/rc.conf
echo "\n";
echo 'alignak_scheduler_enable="YES"' >> /etc/rc.conf
echo "\n";
echo 'alignak_reactionner_enable="YES"' >> /etc/rc.conf
echo "\n";
echo 'alignak_receiver_enable="YES"' >> /etc/rc.conf
echo "\n";
echo 'alignak_arbiter_enable="YES"' >> /etc/rc.conf
echo "\n";
echo 'alignak_arbiter_configfile="/usr/local/etc/alignak/alignak.backend-run.cfg"' >> /etc/rc.conf
echo "\n";


# git clone the check packs
cd /root/git
/usr/local/bin/git clone https://github.com/Alignak-monitoring-contrib/alignak-checks-snmp.git
/usr/local/bin/git clone https://github.com/Alignak-monitoring-contrib/alignak-checks-mysql.git
/usr/local/bin/git clone https://github.com/Alignak-monitoring-contrib/alignak-checks-nrpe.git
/usr/local/bin/git clone https://github.com/Alignak-monitoring-contrib/alignak-checks-windows-nsca.git
/usr/local/bin/git clone https://github.com/Alignak-monitoring-contrib/alignak-checks-wmi.git
/usr/local/bin/git clone https://github.com/Alignak-monitoring-contrib/alignak-checks-monitoring.git
/usr/local/bin/git clone https://github.com/Alignak-monitoring-contrib/alignak-checks-glances.git

/usr/local/bin/git clone https://github.com/Alignak-monitoring-contrib/alignak-notifications.git


# create script to install them that will be run manually after managed the right address of the backend
echo "cd /root/git/alignak-checks-snmp\n" > /root/install_check_packs.sh
echo "pip install .\n" >> /root/install_check_packs.sh

echo "cd /root/git/alignak-checks-mysql\n" >> /root/install_check_packs.sh
echo "pip install .\n" >> /root/install_check_packs.sh

echo "cd /root/git/alignak-checks-nrpe\n" >> /root/install_check_packs.sh
echo "pip install .\n" >> /root/install_check_packs.sh

echo "cd /root/git/alignak-checks-windows-nsca\n" >> /root/install_check_packs.sh
echo "pip install .\n" >> /root/install_check_packs.sh

echo "cd /root/git/alignak-checks-wmi\n" >> /root/install_check_packs.sh
echo "pip install .\n" >> /root/install_check_packs.sh

echo "cd /root/git/alignak-checks-monitoring\n" >> /root/install_check_packs.sh
echo "pip install .\n" >> /root/install_check_packs.sh

echo "cd /root/git/alignak-checks-glances\n" >> /root/install_check_packs.sh
echo "pip install .\n" >> /root/install_check_packs.sh

echo "cd /root/git/alignak-notifications\n" >> /root/install_check_packs.sh
echo "pip install .\n" >> /root/install_check_packs.sh

chmod 755 /root/install_check_packs.sh


# Install example website scenario
mkdir /root/scenarii
cd /root/scenarii

/usr/local/bin/cucumber-nagios-gen project websites
cd websites
/usr/local/bin/bundle install
# patch features/support/env.rb
cat >> features/support/env.rb << EOF

Webrat.configure do |config|
 config.mode = :rails
 config.open_error_files = false
end
EOF

# patch features/steps/http_steps.rb
sed -i '' 's/response.body.to_s.should =~ \/#{text}\/m/expect(response.body).to match(\/#{text}\/m)/g' features/steps/http_steps.rb

# create a website to test
/usr/local/bin/cucumber-nagios-gen feature mywebsite.com glpi

sed -i '' 's/Then the request should succeed//g' features/mywebsite.com/glpi.feature

cat >> features/mywebsite.com/glpi.feature << EOF
    Then I should see "Authentification"
    When I fill in "login_name" with "glpi"
      And I fill in "login_password" with "glpi"
      And I press "Envoyer"
    Then I should see "window.location='/front/central.php'"
    When I go to "https://mywebsite.com/front/central.php"
    Then I should see "Vue personnelle"
    When I follow "Assistance"
    Then I should see "De 1 "
EOF

# modification into cucumber-nagios, to work with ruby 2.x
sed -i '' 's/def initialize(step_mother, io, options={}/def initialize(step_mother, io, options/g' /usr/local/lib/ruby/gems/2.3/gems/cucumber-nagios-0.9.2/lib/cucumber/formatter/nagios.rb
sed -i '' 's/def after_step_result(keyword, step_match, multiline_arg, status, exception, source_indent, background)/def after_step_result(keyword, step_match, multiline_arg, status, exception, source_indent, background, scenario_line_num)/g' /usr/local/lib/ruby/gems/2.3/gems/cucumber-nagios-0.9.2/lib/cucumber/formatter/nagios.rb

# command used for the check in Alignak : cd /root/scenarii/websites && /usr/local/bin/cucumber-nagios features/mywebsite.com/glpi.feature


# Postinstall
##############
#
# Your own stuff here, for example set login shells that were only
# installed just before.

# Please note, that for all network related stuff like ports,
# package remote fetching, etc. you need a sane /etc/resolv.conf

# chpass -s /usr/local/bin/bash admin
# pkg_add -r pico
# cd /usr/ports/sysutils/screen && make install
}

run_rc_command "$1"

